# Generated by Django 3.1.7 on 2021-04-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('mcq_id', models.IntegerField(primary_key=True, serialize=False)),
                ('statement', models.CharField(max_length=256)),
                ('correct_ans', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=100, unique=True)),
                ('total_mcq', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.CharField(max_length=256)),
                ('B', models.CharField(max_length=256)),
                ('C', models.CharField(max_length=256)),
                ('D', models.CharField(max_length=256)),
                ('mcq_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding_api.mcq')),
            ],
        ),
        migrations.AddField(
            model_name='mcq',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding_api.topics'),
        ),
    ]
