# Generated by Django 3.1.7 on 2021-04-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='mcq_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topic_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
