# Generated by Django 3.1.7 on 2021-05-08 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coding_api', '0002_auto_20210406_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='total_mcq',
        ),
        migrations.AlterField(
            model_name='options',
            name='mcq_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='coding_api.mcq'),
        ),
    ]
